### ISSUE TITLE
Allomancy 4.3.0-pre3 Errors in Log

### ISSUE THREAD

**Issue by ClaudiusMinimus** [legobmw99/Allomancy#55] opened 2021-04-22 20:23 UTC
Your Allomancy mod is a big part of my pack [Create on a Potato PC](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato). As I was updating today on my test server I noticed over 1,500 lines of errors for Allomancy. I had not noticed these before, but when I check the prior version many of the same errors were present. 

Thank you for a fun mod! Many of my players are really enjoying being Mistborn. BTW: I am getting about 100 downloads--and growing--a day, and a total of just over 3,000 downloads.

Minecraft 1.16.5
Forge 36.1.0
Allomancy 4.3.0-pre3.jar (also many of these errors were in prior versions)

https://pastebin.com/8vkeesjd

**Comment by legobmw99** [comment] 2021-04-22 20:26
Did any of these errors occur before the 4.3 pre-release? I believe they are caused by the rather haphazard way I removed the extra 4.3 features in order to release the alpha

**Comment by ClaudiusMinimus** [comment] 2021-04-22 20:26
Yes

**Comment by ClaudiusMinimus** [comment] 2021-04-22 20:28
They are also in allomancy-4.2.1

**Comment by legobmw99** [comment] 2021-04-22 20:28
Could you supply a full log from 4.2?

**Comment by ClaudiusMinimus** [comment] 2021-04-22 20:30
[latest.log](https://github.com/legobmw99/Allomancy/files/6361060/latest.log)

**Comment by legobmw99** [comment] 2021-04-22 20:46
I believe that log is still 4.3

**Comment by ClaudiusMinimus** [comment] 2021-04-22 21:08
Purging the logs and restarting the server

**Comment by ClaudiusMinimus** [comment] 2021-04-22 21:10
You were correct, it was 4.3. It seems I was wrong in that 4.2 is fine.

**Comment by legobmw99** [comment] 2021-04-22 21:12
Okay, cool - this will be fixed in the full release of 4.3 (which hopefully will be soon!)

**Closed by legobmw99** 2021-04-22 21:12 UTC
