### ISSUE TITLE
Getting *lots* of "info" messages about your vials...

### ISSUE THREAD

**Issue by MentalMouse** [legobmw99/Allomancy#31] opened 2018-05-05 04:47 UTC
Getting repeated spurts of these messages, while not actually carrying any vials.

> [00:00:25] [Server thread/INFO] [STDOUT]: [com.legobmw99.allomancy.util.RecipeItemVial:func_77569_a:32]: 1
> [00:00:25] [Server thread/INFO] [STDOUT]: [com.legobmw99.allomancy.util.RecipeItemVial:func_77569_a:32]: 1
> [00:00:25] [Server thread/INFO] [STDOUT]: [com.legobmw99.allomancy.util.RecipeItemVial:func_77569_a:32]: 1
> [00:00:25] [Server thread/INFO] [STDOUT]: [com.legobmw99.allomancy.util.RecipeItemVial:func_77569_a:32]: 1
>

**Comment by legobmw99** [comment] 2018-05-05 18:17
Duplicate of #27, fixed but builds on CF are not current

**Closed by legobmw99** 2018-05-05 18:17 UTC

**Comment by MentalMouse** [comment] 2018-05-06 00:36
If not at CurseForge, where are the current builds?

**Comment by legobmw99** [comment] 2018-05-06 01:03
Nowhere currently. It can be built from source, but I haven’t had much time for even the smallest releases lately.

I can probably sometime soon

**Comment by MentalMouse** [comment] 2018-05-06 10:26
OK, thanks -- I understand, real life comes first.  The mod is still working well (and being useful otherwise; I was just wondering if this was connected to some occasional game lag/freezes I'm having. These messages were the oddest thing I saw in my game output, but I _am_ running with 70 or so mods here.
