### ISSUE TITLE
Crashed Server While Steelpushing

### ISSUE THREAD

**Issue by ClaudiusMinimus** [legobmw99/Allomancy#56] opened 2021-04-23 05:11 UTC
Minecraft 1.16.5
Forge 36.1.0
Allomancy 4.2.1
Modpack  [Create on a Potato PC](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato)

I had a player who tried to get into a minecart while steelpushing, and server crashed. 

[crash-2021-04-23_06.43.50-server.txt](https://github.com/legobmw99/Allomancy/files/6362875/crash-2021-04-23_06.43.50-server.txt)

**Comment by legobmw99** [comment] 2021-04-23 12:33
This is a duplicate of #49, which is fixed in 4.3

**Closed by legobmw99** 2021-04-23 12:33 UTC
