### ISSUE TITLE
No Blue Lines

### ISSUE THREAD

**Issue by DanielG75276** [legobmw99/Allomancy#105] opened 2024-08-22 19:49 UTC
When im using the mod i cant see the blue lines from steel and iron. I aldo cant see where electrum and gold point to. Tin is working fine it is just those four that dont point anywhere

**Comment by legobmw99** [comment] 2024-08-22 19:55
Are you using windows?

**Comment by DanielG75276** [comment] 2024-08-22 23:17
> Are you using windows?

Yes I am on windows 10 also besides this issue your mod is awesome im really enjoying it so far

**Comment by legobmw99** [comment] 2024-08-22 23:49
This is a duplicate of #92 then. Unfortunately, we've not yet been able to figure out what exactly causes this -- it's not _all_ Windows users, since I myself am one

**Closed by legobmw99** 2024-08-22 23:49 UTC
